version: '2'
services:
  server:
    environment:
      - 'POSTGRES_HOST=postgres'
      - 'POSTGRES_PORT=5432'
      - 'PORT=8080'
      - 'DB_ENV=prod'
    image: 'sveppalicious/tictactoe:${GIT_COMMIT}'
    ports:
      - '8000:8000'
    links:
      - 'postgres'
  postgres:
    image: 'postgres'
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'
      - 'POSTGRES_USER=postgres'
    expose:
      - '5432'
